url: https://y7kim.github.io
baseurl:

# Site settings
title: Wantonwells Farm Fresh
email: wantonwellsfarm@gmail.com
description: "We are a local organic farm in Aberdeenshire."


# Team names, titles and social links
people:
- name: Beatric Fettes
  pic: beatrice
  position: Head Farmer
  social:
    - title: twitter
      url: Do you have a twitter account?
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Rosie Wilson-Leagas
  pic: rosie
  position: Assistant Chief of Farm Operations
  social:
    - title: linkedin
      url: Rosie Has a linkedin im certain

- name: Fergus Fettes
  pic: brock
  position: Backend Engineer/Hydrogeologist
  social:
    - title: twitter
      url: https://twitter.com/frgnym
    - title: linkedin
      url: https://www.linkedin.com/in/fergus-fettes-433b46173/
    - title: github
      url: https://github.com/fergusfettes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: wantonwellsfarm

# Postal address (add as many lines as necessary)
address:
  - line: Wantonwells Farm
  - line: Insch, Aberdeenshire

# Build settings
markdown: kramdown
permalink: pretty
