url: https://y7kim.github.io
baseurl:

# Site settings
title: Wantonwells Farm Fresh
email: wantonwellsfarm@gmail.com
description: "We are a local organic farm in Aberdeenshire."

colors:
  primary: pink
  # # if you want to do them in hex, you have to quote them lik so
  # primary: '#FFC0CB'
  primary-hex: FFC0CB
  secondary: green
  muted: teal


# Team names, titles and social links
people:
- name: Beatric Fettes
  pic: beatrice
  position: Head Farmer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/beatrice-fettes-46230524/

- name: Rosie Wilson-Leagas
  pic: rosie
  position: Chief Forager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/rosie-wilson-leagas-5997683a

- name: Fergus Fettes
  pic: brock
  position: Backend Engineer/Hydrogeologist
  social:
    - title: twitter
      url: https://twitter.com/frgnym
    - title: linkedin
      url: https://www.linkedin.com/in/fergus-fettes-433b46173/
    - title: github
      url: https://github.com/fergusfettes

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/wantonwellsfarm

# Postal address (add as many lines as necessary)
address:
  - line: Wantonwells Farm
  - line: Insch, Aberdeenshire

# Build settings
markdown: kramdown
permalink: pretty
